import fs from "fs";
import path from "path";
import { Repository } from "typeorm";
import { Customer, CustomerState } from "../customers/src/entities/Customer";

export class RadiusSyncService {
  constructor(private customerRepo: Repository<Customer>, private usersFilePath: string) {}

  async writeUsersFile(existing: Customer[]) {
    const lines: string[] = [];
    lines.push("# FreeRADIUS users file generated by ISPradius");
    lines.push("# Do not edit directly unless you know what you are doing.");
    lines.push("");

    for (const customer of existing) {
      if (customer.state !== CustomerState.ACTIVE) {
        continue;
      }
      const username = customer.email;
      const password = "{{PLACEHOLDER_PASSWORD}}"; // Replace with actual password management

      lines.push(`${username}        Cleartext-Password := "${password}"`);
      lines.push("    Reply-Message := \"Welcome to ISPradius\"");
      lines.push("");
    }

    const output = lines.join("\n");

    await fs.promises.mkdir(path.dirname(this.usersFilePath), { recursive: true });
    await fs.promises.writeFile(this.usersFilePath, output, { encoding: "utf8" });
  }

  async sync() {
    const customers = await this.customerRepo.find();
    await this.writeUsersFile(customers);
  }
}
